#!/bin/bash
case "$ACTION" in
post)
	if [ "$UPDATE" = "no" ]; then
		xdg-user-dirs-update
		layout=$(grep 'KEYMAP=' /etc/rc.conf | cut -d= -f2)
		mkdir -p /usr/share/cosmic/com.system76.CosmicComp/v1/
		touch /usr/share/cosmic/com.system76.CosmicComp/v1/xkb_config
		cat >> /usr/share/cosmic/com.system76.CosmicComp/v1/xkb_config <<EOF
(
rules: "",
model: "",
layout: "us",
variant: "",
options: None,
repeat_delay: 600,
repeat_rate: 25,
)
EOF
		sed -i "s/us/$layout/" /usr/share/cosmic/com.system76.CosmicComp/v1/xkb_config
		if [ ! -h /usr/bin/firefox ]; then
			sed -i 's/firefox//' /usr/share/cosmic/com.system76.CosmicAppList/v1/favorites
		fi
	fi
	;;
esac
