#!/bin/sh
# Shared getty runner for the agetty-* dinit services.
# The GETTY_ARGS="$GETTY_ARGS --noclear" line is matched verbatim by
# noid-mklive's live autologin hook (dracut/vmklive/adduser.sh); keep it.

tty=$1
GETTY_ARGS=""
GETTY_ARGS="$GETTY_ARGS --noclear"

case "$tty" in
	ttyS*) exec /usr/bin/agetty $GETTY_ARGS -L "$tty" 115200 vt100 ;;
	*) exec /usr/bin/agetty $GETTY_ARGS "$tty" 38400 linux ;;
esac
