#!/bin/sh
# dinit-chimera console hook: keymap and font from Void's /etc/rc.conf.
# Called as "dinit-console keyboard" or "dinit-console console".

[ -r /etc/rc.conf ] && . /etc/rc.conf

if [ "$1" = "keyboard" ]; then
	[ -n "$KEYMAP" ] && exec /usr/bin/loadkeys -q "$KEYMAP"
	exit 0
fi

[ -n "$FONT" ] || exit 0
set -- "$FONT"
[ -n "$FONT_MAP" ] && set -- "$@" -m "$FONT_MAP"
[ -n "$FONT_UNIMAP" ] && set -- "$@" -u "$FONT_UNIMAP"
exec /usr/bin/setfont "$@"
