#!/bin/sh
# Prepares the runtime state a daemon expects, then execs it.
# Usage: dinit-dm <name> <command> [args...]

name="$1"
shift

case "$name" in
lightdm)
	install -d -m0711 -o lightdm -g lightdm /run/lightdm
	;;
gdm)
	if [ ! -d /run/gdm ]; then
		mkdir -m0711 -p /run/gdm
		chown root:gdm /run/gdm
	fi
	;;
sddm)
	[ -r /etc/locale.conf ] && . /etc/locale.conf && export LANG
	if [ -x /usr/bin/elogind-inhibit ]; then
		dbus-send --system --print-reply --dest=org.freedesktop.DBus \
			/org/freedesktop/DBus org.freedesktop.DBus.StartServiceByName \
			string:org.freedesktop.login1 uint32:0 >/dev/null
	fi
	;;
cosmic-greeter-daemon)
	install -d -m0755 -o _cosmicgreeter -g _cosmicgreeter /run/cosmic-greeter
	;;
chronyd)
	install -d -m750 -o chrony -g chrony /var/run/chrony
	;;
esac

exec "$@"
