#!/bin/sh
# dinit-void device manager hook, backed by Void's eudev.

case "$1" in
	start) exec /usr/bin/udevd --daemon ;;
	stop) /usr/bin/udevadm control -e; exit 0 ;;
	settle) exec /usr/bin/udevadm settle ;;
	trigger) exec /usr/bin/udevadm trigger --action=add ;;
esac

echo "dinit-devd: unknown action: $1" >&2
exit 1
